let productsDB=[
    {
        id:1,
        title:"شركة الفندي",
        title2:"انقر لعرض الصور",
        desc:'بيع جميع انواع السيارات والصناديق',
        size:"large",
        imageUrl1:"images/img1.jpg",
        imageUrl2:"images/img1.jpg",
        imageUrl3:"images/img1.jpg",
        qty:1,
        isMe:"N",
    },
     {
        id:1,
        title:"HYUNDA",
        title2:"انقر لعرض الصور",
        desc:'بيع جميع انواع السيارات والصناديق',
        size:"large",
        imageUrl1:"images/HYUNDA.jpg",
        imageUrl2:"images/HYUNDA.jpg",
        imageUrl3:"images/HYUNDA.jpg",
        qty:1,
        isMe:"N",
    },
     {
        id:1,
        title:"isusu",
        title2:"انقر لعرض الصور",
        desc:'بيع جميع انواع السيارات والصناديق',
        size:"large",
        imageUrl1:"images/isusu.jpg",
        imageUrl2:"images/isusu.jpg",
        imageUrl3:"images/isusu.jpg",
        qty:1,
        isMe:"N",
    },
     {
        id:1,
        title:"kia2700",
        title2:"انقر لعرض الصور",
        desc:'بيع جميع انواع السيارات والصناديق',
        size:"medium",
        imageUrl1:"images/kia2700.jpg",
        imageUrl2:"images/kia2700.jpg",
        imageUrl3:"images/kia2700.jpg",
        qty:1,
        isMe:"N",
    },
     {
        id:1,
        title:"kia4000",
        title2:"انقر لعرض الصور",
        desc:'بيع جميع انواع السيارات والصناديق',
        size:"small",
        imageUrl1:"images/kia4000.jpg",
        imageUrl2:"images/kia4000.jpg",
        imageUrl3:"images/kia4000.jpg",
        qty:1,
        isMe:"N",
    },
     {
        id:1,
        title:"blastc",
        title2:"انقر لعرض الصور",
        desc:'بيع جميع انواع السيارات والصناديق',
        size:"small",
        imageUrl1:"images/blastc.jpg",
        imageUrl2:"images/blastc.jpg",
        imageUrl3:"images/blastc.jpg",
        qty:1,
        isMe:"N",
    },
    
];
